name: Create PR to Develop

on:
  workflow_run:
    workflows: ["Angular CI Pipeline"]
    types:
      - completed

jobs:
  open-pr-develop:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (startsWith(github.event.workflow_run.head_branch, 'feat/') ||
       startsWith(github.event.workflow_run.head_branch, 'fix/') ||
       startsWith(github.event.workflow_run.head_branch, 'feature/'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Open Pull Request to develop
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: ${{ github.event.workflow_run.head_branch }}
          destination_branch: develop
          pr_title: "Merge ${{ github.event.workflow_run.head_branch }} into develop"
          pr_body: |
            PR autom√°tica criada pelo pipeline.
            Branch de origem: `${{ github.event.workflow_run.head_branch }}`
