name: Angular CI Pipeline

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'feature/*'

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci-angular.yml
    with:
      branch-name: ${{ github.ref_name }}
      build-path: dist/vyracare-app-shell

  open-pr-develop:
    runs-on: ubuntu-latest
    needs: call-ci-workflow
    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/fix/') || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}         # Use PAT instead of GITHUB_TOKEN
          branch: ${{ github.ref_name }}          # branch de origem
          base: develop                            # branch destino
          commit-message: "chore: merge branch ${{ github.ref_name }} into develop"
          title: "Merge ${{ github.ref_name }} into develop"
          body: |
            PR autom√°tica criada pelo pipeline.
            Branch de origem: `${{ github.ref_name }}`
